package datasupply

import "fmt"

// start OMIT
// Bid contains amount and age of bid
type Bid struct {
	Amount int
	Age    int
	name   string
}

// NewBid : creat a new bid
func NewBid(amount int, age int) *Bid {
	bid := Bid{Amount: amount, Age: age, name: "autogenerated"}
	return &bid
}

// bid OMIT
type hBid struct {
	amount int
	age    int
}

func NewHBid(amount int, age int) *hBid {
	bid := hBid{amount: amount, age: age}
	return &bid
}

func (h hBid) DoSomething() {
	fmt.Println("ok ok, I'm doing it", h.age)
}

// end OMIT
